# Cloud Deploy and Cloud Run configuration

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-pipeline
  description: Cloud Run application pipeline
serialPipeline:
  stages:
    - targetId: run-production-1
    - targetId: run-production-2

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-production-1
  description: "Cloud Run Production Target 1"
run:
  location: ${_REGION}

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-production-2
  description: "Cloud Run Production Target 2"
run:
  location: ${_REGION}

---
apiVersion: run.googleapis.com/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "80"
    spec:
      containers:
        - image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/app-1:V1.0
          ports:
            - containerPort: 3000
          env:
            - name: App-GCP-Service
              value: "App-GCP"
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
