steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git fetch origin features
        git checkout features

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Creating .env file..."
        echo "PORT=$(gcloud secrets versions access latest --secret=PORT)" >> Application/.env
        echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=JWT_SECRET)" >> Application/.env
        echo "GCP_KEYFILE_PATH=$(gcloud secrets versions access latest --secret=GCP_KEYFILE_PATH)" >> Application/.env
        echo "GCP_BUCKET_TEMPORARY=$(gcloud secrets versions access latest --secret=GCP_BUCKET_TEMPORARY)" >> Application/.env
        echo "GCP_BUCKET_MAIN=$(gcloud secrets versions access latest --secret=GCP_BUCKET_MAIN)" >> Application/.env
        echo "FIREBASE_DB_URL=$(gcloud secrets versions access latest --secret=FIREBASE_DB_URL)" >> Application/.env
        echo "FUNCTION_COPY_URL=$(gcloud secrets versions access latest --secret=FUNCTION_COPY_URL)" >> Application/.env
        echo "FUNCTION_DELETE_URL=$(gcloud secrets versions access latest --secret=FUNCTION_DELETE_URL)" >> Application/.env

  - name: "node:18"
    entrypoint: "bash"
    dir: "Application"
    args: [npm install]

  - name: "node:18"
    entrypoint: "bash"
    dir: "Application"
    args: [npm test]

  - name: "gcr.io/cloud-builders/docker"
    dir: "Application"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/app:V1.0",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    dir: "Application"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPOSITORY_NAME/app:V1.0",
      ]

substitutions:
  _PROJECT_ID: networking-438508
  _REPOSITORY_NAME: app-gcp
  _REGION: europe-west1

logsBucket: "gs://matvey-ci-cd"
serviceAccount: "matvey-admin@networking-438508.iam.gserviceaccount.com"
