apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-pipeline
  description: Cloud Run application pipeline
serialPipeline:
  stages:
    - targetId: run-production-1
    - targetId: run-production-2
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-production-1
  description: "Cloud Run Production Target 1"
run:
  location: ${_REGION}
  service: cloud-run-service
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-production-2
  description: "Cloud Run Production Target 2"
run:
  location: ${_REGION}
  service: cloud-run-service
