apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/networking-438508/app:V1.0
      context: Application
      docker:
        dockerfile: Dockerfile
deploy:
  cloudrun:
    region: europe-west1
